export const FLAGS = {
  Argentina: '🇦🇷',
  France: '🇫🇷',
  Brazil: '🇧🇷',
  England: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  Portugal: '🇵🇹',
  Spain: '🇪🇸',
  Netherlands: '🇳🇱',
  Belgium: '🇧🇪',
  Colombia: '🇨🇴',
  Germany: '🇩🇪',
  Uruguay: '🇺🇾',
  Croatia: '🇭🇷',
  Morocco: '🇲🇦',
  Japan: '🇯🇵',
  'United States': '🇺🇸',
  Mexico: '🇲🇽',
  Ecuador: '🇪🇨',
  Turkey: '🇹🇷',
  Iran: '🇮🇷',
  'South Korea': '🇰🇷',
  Australia: '🇦🇺',
  Austria: '🇦🇹',
  Switzerland: '🇨🇭',
  Sweden: '🇸🇪',
  Scotland: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  Norway: '🇳🇴',
  'Congo DR': '🇨🇩',
  Egypt: '🇪🇬',
  Senegal: '🇸🇳',
  Tunisia: '🇹🇳',
  Algeria: '🇩🇿',
  Iraq: '🇮🇶',
  'Saudi Arabia': '🇸🇦',
  'Ivory Coast': '🇨🇮',
  Canada: '🇨🇦',
  Qatar: '🇶🇦',
  Jordan: '🇯🇴',
  Uzbekistan: '🇺🇿',
  Ghana: '🇬🇭',
  Paraguay: '🇵🇾',
  Panama: '🇵🇦',
  'South Africa': '🇿🇦',
  'Bosnia-Herzegovina': '🇧🇦',
  'New Zealand': '🇳🇿',
  Haiti: '🇭🇹',
  'Curaçao': '🇨🇼',
  'Cape Verde Islands': '🇨🇻',
  Czechia: '🇨🇿',
}

export const getFlag = (team) => FLAGS[team] ?? '⚽'
